const CountryIdToCode = [
  [ 203,   'ABW', 'Aruba',  ],
  [   4, 'AFG', 'Afghanistan',  ],
  [   6, 'AGO', 'Angola',  ],
  [ 189, 'ALB', 'Albanien',  ],
  [ 190, 'AND', 'Andorra',  ],
  [ 177, 'ARE', 'Vereinigte Arabische Emirate',  ],
  [   8, 'ARG', 'Argentinien',  ],
  [   9, 'ARM', 'Armenien',  ],
  [ 142, 'ASM', 'Amerikanisch-Samoa',  ],
  [   7, 'ATG', 'Antigua und Barbuda',  ],
  [  10, 'AUS', 'Australien',  ],
  [  11, 'AUT', 'Österreich',  ],
  [  12, 'AZE', 'Aserbaidschan',  ],
  [  26, 'BDI', 'Burundi',  ],
  [ 192, 'BEL', 'Belgien',  ],
  [  17, 'BEN', 'Benin',  ],
  [  25, 'BFA', 'Burkina Faso',  ],
  [ 191, 'BGD', 'Bangladesch',  ],
  [  24, 'BGR', 'Bulgarien',  ],
  [ 200, 'BHR', 'Bahrain',  ],
  [  13, 'BHS', 'Bahamas',  ],
  [  20, 'BIH', 'Bosnien und Herzegowina',  ],
  [  15, 'BLR', 'Weißrussland',  ],
  [  16, 'BLZ', 'Belize',  ],
  [ 205, 'BMU', 'Bermuda',  ],
  [  19, 'BOL', 'Bolivien',  ],
  [  22, 'BRA', 'Brasilien',  ],
  [  14, 'BRB', 'Barbados',  ],
  [  23, 'BRN', 'Brunei Darussalam',  ],
  [  18, 'BTN', 'Bhutan',  ],
  [  21, 'BWA', 'Botswana',  ],
  [  31, 'CAF', 'Zentralafrikanische Republik',  ],
  [  29, 'CAN', 'Kanada',  ],
  [ 162, 'CHE', 'Schweiz',  ],
  [ 206, 'CHI', 'Chile',  ],
  [  33, 'CHL', 'Chile',  ],
  [  34, 'CHN', 'China',  ],
  [  39, 'CIV', 'Elfenbeinküste',  ],
  [  28, 'CMR', 'Kamerun',  ],
  [  44, 'COD', 'Demokratische Republik Kongo',  ],
  [  37, 'COG', 'Kongo',  ],
  [  35, 'COL', 'Kolumbien',  ],
  [  36, 'COM', 'Komoren',  ],
  [  30, 'CPV', 'Kap Verde',  ],
  [  38, 'CRI', 'Costa Rica',  ],
  [  41, 'CUB', 'Kuba',  ],
  [ 207, 'CUW', 'Curaçao',  ],
  [ 208, 'CYM', 'Kaimaninseln',  ],
  [  42, 'CYP', 'Zypern',  ],
  [  43, 'CZE', 'Tschechien',  ],
  [  64, 'DEU', 'Deutschland', ],
  [ 193, 'DJI', 'Dschibuti', ],
  [  46, 'DMA', 'Dominica', ],
  [  45, 'DNK', 'Dänemark', ],
  [  47, 'DOM', 'Dominikanische Republik', ],
  [   5, 'DZA', 'Algerien', ],
  [  49, 'ECU', 'Ecuador', ],
  [  50, 'EGY', 'Ägypten', ],
  [  53, 'ERI', 'Eritrea', ],
  [ 157, 'ESP', 'Spanien', ],
  [  54, 'EST', 'Estland', ],
  [  56, 'ETH', 'Äthiopien', ],
  [  58, 'FIN', 'Finnland', ],
  [  57, 'FJI', 'Fidschi', ],
  [  59, 'FRA', 'Frankreich', ],
  [ 211, 'FRO', 'Färöer', ],
  [ 108, 'FSM', 'Mikronesien', ],
  [  61, 'GAB', 'Gabun', ],
  [ 178, 'GBR', 'Vereinigtes Königreich', ],
  [  63, 'GEO', 'Georgien', ],
  [  65, 'GHA', 'Ghana', ],
  [ 212, 'GIB', 'Gibraltar', ],
  [  70, 'GIN', 'Guinea', ],
  [  62, 'GMB', 'Gambia', ],
  [  71, 'GNB', 'Guinea-Bissau', ],
  [  52, 'GNQ', 'Äquatorialguinea', ],
  [  66, 'GRC', 'Griechenland', ],
  [  68, 'GRD', 'Grenada', ],
  [  67, 'GRL', 'Grönland', ],
  [  69, 'GTM', 'Guatemala', ],
  [   2, 'GUM', 'Guam', ],
  [  72, 'GUY', 'Guyana', ],
  [ 123, 'HKG', 'Hongkong', ],
  [  74, 'HND', 'Honduras', ],
  [  40, 'HRV', 'Kroatien', ],
  [  73, 'HTI', 'Haiti', ],
  [  75, 'HUN', 'Ungarn', ],
  [  78, 'IDN', 'Indonesien' ],
  [ 214, 'IMN', 'Isle of Man', ],
  [  77, 'IND', 'Indien', ],
  [  81, 'IRL', 'Irland', ],
  [  79, 'IRN', 'Iran', ],
  [  80, 'IRQ', 'Irak', ],
  [  76, 'ISL', 'Island', ],
  [  82, 'ISR', 'Israel', ],
  [  83, 'ITA', 'Italien', ],
  [  84, 'JAM', 'Jamaika', ],
  [  86, 'JOR', 'Jordanien', ],
  [  85, 'JPN', 'Japan', ],
  [  87, 'KAZ', 'Kasachstan', ],
  [  88, 'KEN', 'Kenia', ],
  [  91, 'KGZ', 'Kirgisistan', ],
  [  27, 'KHM', 'Kambodscha', ],
  [  89, 'KIR', 'Kiribati', ],
  [ 139, 'KNA', 'St. Kitts und Nevis', ],
  [ 155, 'KOR', 'Südkorea', ],
  [ 201, 'KWT', 'Kuwait', ],
  [  92, 'LAO', 'Laos', ],
  [  94, 'LBN', 'Libanon', ],
  [  95, 'LBR', 'Liberia', ],
  [  96, 'LBY', 'Libyen', ],
  [ 140, 'LCA', 'St. Lucia', ],
  [ 194, 'LIE', 'Liechtenstein', ],
  [ 158, 'LKA', 'Sri Lanka', ],
  [ 195, 'LSO', 'Lesotho', ],
  [  97, 'LTU', 'Litauen', ],
  [  98, 'LUX', 'Luxemburg', ],
  [  93, 'LVA', 'Lettland', ],
  [ 215, 'MAC', 'Macao', ],
  [  60, 'MAF', 'St. Martin', ],
  [ 112, 'MAR', 'Marokko', ],
  [ 196, 'MCO', 'Monaco', ],
  [ 109, 'MDA', 'Republik Moldau', ],
  [  99, 'MDG', 'Madagaskar', ],
  [ 102, 'MDV', 'Malediven', ],
  [ 107, 'MEX', 'Mexiko', ],
  [ 209, 'MHL', 'Marshallinseln', ],
  [ 125, 'MKD', 'Nordmazedonien', ],
  [ 103, 'MLI', 'Mali', ],
  [ 104, 'MLT', 'Malta', ],
  [ 114, 'MMR', 'Myanmar', ],
  [ 111, 'MNE', 'Montenegro', ],
  [ 110, 'MNG', 'Mongolei', ],
  [ 217, 'MNP', 'Nördliche Marianen', ],
  [ 113, 'MOZ', 'Mosambik', ],
  [ 105, 'MRT', 'Mauretanien', ],
  [ 106, 'MUS', 'Mauritius', ],
  [ 100, 'MWI', 'Malawi', ],
  [ 101, 'MYS', 'Malaysia', ],
  [ 115, 'NAM', 'Namibia', ],
  [ 119, 'NCL', 'Neukaledonien', ],
  [ 122, 'NER', 'Niger', ],
  [ 123, 'NGA', 'Nigeria', ],
  [ 121, 'NIC', 'Nicaragua', ],
  [ 118, 'NLD', 'Niederlande', ],
  [ 197, 'NOR', 'Norwegen', ],
  [ 117, 'NPL', 'Nepal', ],
  [ 116, 'NRU', 'Nauru', ],
  [ 120, 'NZL', 'Neuseeland', ],
  [ 198, 'OMN', 'Oman', ],
  [ 126, 'PAK', 'Pakistan', ],
  [ 128, 'PAN', 'Panama', ],
  [ 131, 'PER', 'Peru', ],
  [ 132, 'PHL', 'Philippinen', ],
  [   3, 'PLW', 'Palau', ],
  [ 129, 'PNG', 'Papua-Neuguinea', ],
  [ 133, 'POL', 'Polen', ],
  [ 135, 'PRI', 'Puerto Rico', ],
  [ 124, 'PRK', 'Nordkorea', ],
  [ 134, 'PRT', 'Portugal', ],
  [ 130, 'PRY', 'Paraguay', ],
  [ 127, 'PSE', 'Palästinensische Autonomiegebiete', ],
  [ 169, 'PYF', 'Französisch-Polynesien', ],
  [ 202, 'QAT', 'Katar', ],
  [ 136, 'ROU', 'Rumänien', ],
  [ 137, 'RUS', 'Russland', ],
  [ 138, 'RWA', 'Ruanda', ],
  [ 144, 'SAU', 'Saudi-Arabien', ],
  [ 159, 'SDN', 'Sudan', ],
  [ 145, 'SEN', 'Senegal', ],
  [ 149, 'SGP', 'Singapur', ],
  [ 152, 'SLB', 'Salomonen', ],
  [ 148, 'SLE', 'Sierra Leone', ],
  [  51, 'SLV', 'El Salvador', ],
  [ 199, 'SMR', 'San Marino', ],
  [ 153, 'SOM', 'Somalia', ],
  [ 146, 'SRB', 'Serbien', ],
  [ 156, 'SSD', 'Südsudan', ],
  [ 143, 'STP', 'São Tomé und Príncipe', ],
  [ 160, 'SUR', 'Suriname', ],
  [ 150, 'SVK', 'Slowakei', ],
  [ 151, 'SVN', 'Slowenien', ],
  [ 161, 'SWE', 'Schweden', ],
  [  55, 'SWZ', 'Eswatini', ],
  [ 216, 'SXM', 'Sint Maarten', ],
  [ 147, 'SYC', 'Seychellen', ],
  [ 163, 'SYR', 'Syrien', ],
  [ 218, 'TCA', 'Turks- und Caicosinseln', ],
  [  32, 'TCD', 'Tschad', ],
  [ 168, 'TGO', 'Togo', ],
  [ 167, 'THA', 'Thailand', ],
  [ 165, 'TJK', 'Tadschikistan', ],
  [ 173, 'TKM', 'Turkmenistan', ],
  [  48, 'TLS', 'Osttimor', ],
  [ 210, 'TON', 'Tonga', ],
  [ 170, 'TTO', 'Trinidad und Tobago', ],
  [ 171, 'TUN', 'Tunesien', ],
  [ 172, 'TUR', 'Türkei', ],
  [ 174, 'TUV', 'Tuvalu', ],
  [ 166, 'TZA', 'Tansania', ],
  [ 175, 'UGA', 'Uganda', ],
  [ 176, 'UKR', 'Ukraine', ],
  [ 180, 'URY', 'Uruguay', ],
  [ 179, 'USA', 'Vereinigte Staaten', ],
  [ 181, 'UZB', 'Usbekistan', ],
  [ 141, 'VCT', 'St. Vincent und die Grenadinen', ],
  [ 183, 'VEN', 'Venezuela', ],
  [ 219, 'VGB', 'Britische Jungferninseln', ],
  [ 220, 'VIR', 'Amerikanische Jungferninseln', ],
  [ 184, 'VNM', 'Vietnam', ],
  [ 182, 'VUT', 'Vanuatu', ],
  [ 204, 'WSM', 'Samoa', ],
  [  91, 'XKX', 'Kosovo', ],
  [ 186, 'YEM', 'Jemen', ],
  [ 154, 'ZAF', 'Südafrika', ],
  [ 187, 'ZMB', 'Sambia', ],
  [ 188, 'ZWE', 'Simbabwe', ],
]

export default CountryIdToCode
