# name: Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [16.x] # You can adjust the Node.js version as needed

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Install and build
#         run: |
#           cd gui
#           npm install
#           npm run build

#       - name: Debug
#         run: |
#           echo "Current directory: $(pwd)"
#           echo "List files: $(ls -la)"
#           git status

#       - name: Deploy
#         uses: JamesIves/github-pages-deploy-action@v4
#         with:
#           branch: main # Change this to the branch you want to deploy to
#           folder: gui/build # Change this to the correct folder path
#           token: ${{ secrets.DEPLOY_SECRET }}
#           clean: true
#           force: true
